repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
            args: [--allow-multiple-documents]

  -   repo: https://github.com/PyCQA/bandit
      rev: 1.7.4
      hooks:
        - id: bandit
          exclude: tests
          args: [--skip, "B101"]
  -   repo: https://github.com/PyCQA/pydocstyle
      rev: 6.1.1
      hooks:
        - id: pydocstyle
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.971'
      hooks:
        - id: mypy
  -   repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
        - id: isort
  -   repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
        - id: flake8
          args:
            - "--max-line-length=160"
