version: 2

sources:
  - name: census_public
    schema: census_public
    tables:
      - name: census_v1
        description: >
            This source table is actually a set of files in external storage.
            The dbt-external-tables package provides handy macros for getting
            those files queryable, just in time for modeling.

        external:
          location: "gs://sample-data-engineering-census-public-source/census.csv"
          options:
            format: CSV