---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: credentials
  labels:
    app: credentials
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: credentials
    namespace: airflow
  capacity:
    storage: 5Mi
  hostPath:
    path: /tmp/credentials

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credentials
  namespace: airflow
  labels:
    app: credentials
spec:
  volumeName: credentials
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
